#:schema https://mago.carthage.software/1.47.2/schema.json
version = "1"
php-version = "8.4.0"

[source]
workspace = "."
paths = ["src"]
includes = ["vendor"]
excludes = []

[source.glob]
literal-separator = true

[formatter]
function-brace-style = "same-line"
method-brace-style = "same-line"
classlike-brace-style = "same-line"

[linter]
integrations = []

[linter.rules]
ambiguous-function-call = { enabled = true }
literal-named-argument = { enabled = false }
prefer-early-continue = { enabled = false }
no-isset = { enabled = false }

cyclomatic-complexity = { enabled = false }
excessive-parameter-list = { enabled = false }
kan-defect = { enabled = false }
too-many-methods = { enabled = false }
halstead = { effort-threshold = 7000 }
no-else-clause = { enabled = false }

no-fully-qualified-global-class-like = { enabled = true }
no-fully-qualified-global-constant = { enabled = true }
no-fully-qualified-global-function = { enabled = true }
